const Router = require('express')
const facultyRouter = require('./facultyRouter')
const departmentRouter = require('./departmentRouter')
const termRouter = require('./termRouter')
const teacherRouter = require('./teacherRouter')
const studentRouter = require('./studentRouter')
const groupRouter = require('./groupRouter')
const gradeRouter = require('./gradeRouter')
const disciplineRouter = require('./disciplineRouter')
const fileRouter = require('./fileRouter')
//
const router = new Router()
router.use('/faculty', facultyRouter)
router.use('/department', departmentRouter)
router.use('/term', termRouter)
router.use('/teacher', teacherRouter)
router.use('/student', studentRouter)
router.use('/group', groupRouter)
router.use('/grade', gradeRouter)
router.use('/discipline', disciplineRouter)
router.use('/savefile', fileRouter)
module.exports = router
