export const variables = {
  API_URL: 'http://localhost:5000/Refs/',
  PHOTO_URL: 'http://localhost:5000/static/'
}

export const ACTION_TYPES = {
  CREATE_STUDENT: 'CREATE_STUDENT',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  FETCH_ALL_STUDENT: 'FETCH_ALL_STUDENT',

  CREATE_FACULTY: 'CREATE_FACULTY',
  UPDATE_FACULTY: 'UPDATE_FACULTY',
  DELETE_FACULTY: 'DELETE_FACULTY',
  FETCH_ALL_FACULTY: 'FETCH_ALL_FACULTY',

  CREATE_GROUP: 'CREATE_GROUP',
  UPDATE_GROUP: 'UPDATE_GROUP',
  DELETE_GROUP: 'DELETE_GROUP',
  FETCH_ALL_GROUP: 'FETCH_ALL_GROUP',

  CREATE_TEACHER: 'CREATE_TEACHER',
  UPDATE_TEACHER: 'UPDATE_TEACHER',
  DELETE_TEACHER: 'DELETE_TEACHER',
  FETCH_ALL_TEACHER: 'FETCH_ALL_TEACHER',

  CREATE_DISCIPLINE: 'CREATE_DISCIPLINE',
  UPDATE_DISCIPLINE: 'UPDATE_DISCIPLINE',
  DELETE_DISCIPLINE: 'DELETE_DISCIPLINE',
  FETCH_ALL_DISCIPLINE: 'FETCH_ALL_DISCIPLINE',

  CREATE_TERM: 'CREATE_TERM',
  UPDATE_TERM: 'UPDATE_TERM',
  DELETE_TERM: 'DELETE_TERM',
  FETCH_ALL_TERM: 'FETCH_ALL_TERM',

  CREATE_GRADE: 'CREATE_GRADE',
  UPDATE_GRADE: 'UPDATE_GRADE',
  DELETE_GRADE: 'DELETE_GRADE',
  FETCH_ALL_GRADE: 'FETCH_ALL_GRADE',

  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',
  FETCH_ALL_DEPARTMENT: 'FETCH_ALL_DEPARTMENT'

}
